name: actions-check

on:
  pull_request:
    branches:
      - main
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'

