# This is a basic workflow to help you get started with Actions

name: better-merge-checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy: 
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest] 
        r: [4.0.3, 3.6.3, 3.4.3]
    
    runs-on: ${{ matrix.os }} 
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Environment tests
        #uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with: 
          r-version: ${{ matrix.r }}
      #- name: Install BiocSwirl Dependencies
      #  run: | 

      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: $ {{ secrets.GITHUB_TOKEN }}
          # Comment to post on an individual's first issue
          issue-message: "Good first issue" # optional
          # Comment to post on an individual's first pull request
          pr-message: "Congratulations on your first Pull Request!" # optional
