# This is a basic workflow to help you get started with Actions

name: better-merge-checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1' ]
    name: check_sample
    steps:
    - uses: actions/checkout@v2
    - name: Get Directory
      run: ls ${{ github.workspace }}
    - name: setup-r
      uses: r-lib/actions/setup-r@v1
      with: 
        r-version: ${{ matrix.R }}
    - run: Rscript -e 'print("hello")'
        
      
